#!/usr/bin/env bash
# ============================================================
# GestionMonetaria — Server bootstrap
#
# Usage:
#   sudo ./deploy/bootstrap.sh
#
# What it does:
#   1. Installs system dependencies (Docker, Node.js, nginx, certbot)
#   2. Reads config.yml + .env.production
#   3. Clones / pulls the app repository
#   4. Starts Supabase via Docker Compose
#   5. Generates nginx site config and obtains SSL certificate
#   6. Creates systemd service for the Next.js app
#   7. Builds and starts the app
#
# Prerequisites:
#   - Debian 12+ (bookworm)
#   - Root / sudo access
#   - Domain DNS already pointing to this server
#   - Ports 80 and 443 reachable (no firewall block)
# ============================================================
set -euo pipefail

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*"; }

# --- Sanity checks ---
if [[ $EUID -ne 0 ]]; then
    err "This script must be run as root (sudo)."
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

if [[ ! -f config.yml ]]; then
    err "config.yml not found in $SCRIPT_DIR"
    exit 1
fi

# --- Parse config.yml (simple grep-based, no yq dependency) ---
get_yaml() {
    grep -E "^${1}:" config.yml | sed "s/^${1}: *\"\?//" | sed 's/\"$//' | tr -d ' '
}

DOMAIN=$(get_yaml "domain.name")
SSL_EMAIL=$(get_yaml "domain.ssl_email")
REPO_URL=$(get_yaml "app.repo_url")
DEPLOY_PATH=$(get_yaml "app.deploy_path")
NODE_VERSION=$(get_yaml "app.node_version")
APP_PORT=$(get_yaml "app.port")
SUPABASE_PROJECT=$(get_yaml "supabase.project_name")
API_PORT=$(get_yaml "supabase.api_port")
DB_PORT=$(get_yaml "supabase.db_port")
STUDIO_PORT=$(get_yaml "supabase.studio_port")
TIMEZONE=$(get_yaml "system.timezone")

# --- Validate required fields ---
if [[ "$DOMAIN" == "tudominio.com" || -z "$DOMAIN" ]]; then
    err "You must set 'domain.name' in config.yml to your actual domain."
    exit 1
fi

if [[ "$REPO_URL" == "https://github.com/tuusuario/gestion-monetaria.git" || -z "$REPO_URL" ]]; then
    err "You must set 'app.repo_url' in config.yml to your repository URL."
    exit 1
fi

if [[ ! -f .env.production ]]; then
    err ".env.production not found."
    err "Copy .env.production.example to .env.production and fill in your secrets."
    exit 1
fi

# --- Load secrets (safe: only exported for the script, not written to disk) ---
set -a
source .env.production
set +a

if [[ -z "${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}" || \
      -z "${SUPABASE_SERVICE_ROLE_KEY:-}" || \
      -z "${SUPABASE_DB_PASSWORD:-}" ]]; then
    err ".env.production is missing required keys (SUPABASE_ANON_KEY, SERVICE_ROLE_KEY, DB_PASSWORD)."
    exit 1
fi

NODE_BIN="/usr/local/bin/node"

# ============================================================
# STEP 1: Install system dependencies
# ============================================================
step_system() {
    info "Step 1/7 — Installing system dependencies..."

    export DEBIAN_FRONTEND=noninteractive

    apt-get update -qq
    apt-get install -y -qq \
        curl git nginx certbot python3-certbot-nginx \
        ca-certificates gnupg lsb-release

    # --- Docker ---
    if ! command -v docker &>/dev/null; then
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/debian/gpg \
            -o /etc/apt/keyrings/docker.asc
        chmod 644 /etc/apt/keyrings/docker.asc
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
            https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
            > /etc/apt/sources.list.d/docker.list
        apt-get update -qq
        apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
        systemctl enable --now docker
        ok "Docker installed"
    else
        ok "Docker already installed"
    fi

    # --- Node.js ---
    if ! command -v node &>/dev/null || [[ "$(node --version | cut -d. -f1 | tr -d v)" -lt "$NODE_VERSION" ]]; then
        curl -fsSL "https://deb.nodesource.com/setup_${NODE_VERSION}.x" | bash -
        apt-get install -y -qq nodejs
        ok "Node.js $(node --version) installed"
    else
        ok "Node.js $(node --version) already installed"
    fi

    # --- Timezone ---
    timedatectl set-timezone "$TIMEZONE" 2>/dev/null || true

    ok "System dependencies ready"
}

# ============================================================
# STEP 2: Clone / pull repository
# ============================================================
step_repo() {
    info "Step 2/7 — Ensuring repository at $DEPLOY_PATH..."

    if [[ -d "$DEPLOY_PATH/.git" ]]; then
        info "Repository exists — pulling latest..."
        git -C "$DEPLOY_PATH" pull --ff-only
    else
        mkdir -p "$(dirname "$DEPLOY_PATH")"
        git clone "$REPO_URL" "$DEPLOY_PATH"
    fi

    ok "Repository ready at $DEPLOY_PATH"
}

# ============================================================
# STEP 3: Set up Supabase Docker
# ============================================================
step_supabase() {
    info "Step 3/7 — Configuring and starting Supabase..."

    local SUPABASE_DIR="$DEPLOY_PATH/supabase"

    if [[ ! -f "$SUPABASE_DIR/docker-compose.yml" ]]; then
        err "Supabase docker-compose.yml not found at $SUPABASE_DIR"
        exit 1
    fi

    # Generate Supabase .env if not present
    if [[ ! -f "$SUPABASE_DIR/.env" ]]; then
        cat > "$SUPABASE_DIR/.env" <<SUPABASE_ENV
POSTGRES_PASSWORD=${SUPABASE_DB_PASSWORD}
JWT_SECRET=$(openssl rand -hex 32)
ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
DASHBOARD_USERNAME=admin
DASHBOARD_PASSWORD=${SUPABASE_DB_PASSWORD}
SUPABASE_URL=http://127.0.0.1:${API_PORT}
STUDIO_PORT=${STUDIO_PORT}
SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}
SUPABASE_DB_HOST=db
SUPABASE_DB_PORT=5432
SUPABASE_DB_NAME=postgres
SUPABASE_DB_USER=postgres
SUPABASE_DB_PASS=${SUPABASE_DB_PASSWORD}
API_EXTERNAL_URL=http://127.0.0.1:${API_PORT}
GOTRUE_EXTERNAL_URL=http://127.0.0.1:${API_PORT}
SUPABASE_PUBLIC_URL=http://127.0.0.1:${API_PORT}
SUPABASE_AUTH_EXTERNAL_URL=http://127.0.0.1:${API_PORT}
SUPABASE_STORAGE_S3_ACCESS_KEY=
SUPABASE_STORAGE_S3_SECRET_KEY=
SUPABASE_STORAGE_S3_REGION=us-east-1
SUPABASE_STORAGE_S3_BUCKET=stub
SUPABASE_STORAGE_FILE_SIZE_LIMIT=52428800
SUPABASE_MAX_ROWS=1000
SUPABASE_DB_POOL_SIZE=10
SUPABASE_DB_EXTRA_SEARCH_PATH=public
SUPABASE_LOG_LEVEL=error
SUPABASE_ENABLE_ANALYTICS=true
SUPABASE_ENABLE_LOGS=true
SUPABASE_ENABLE_PG_SINONIMOS=true
SUPABASE_ENABLE_PG_CRYPTO=true
SUPABASE_ENABLE_PG_NET=true
SUPABASE_ENABLE_PG_GRAPHQL=true
SUPABASE_ENABLE_PG_POSTGIS=false
SUPABASE_ENABLE_PG_AUDIT=false
SUPABASE_ENABLE_PG_HYPERTABLE=false
SUPABASE_ENABLE_PG_VECTOR=false
SUPABASE_REST_URL=http://127.0.0.1:${API_PORT}/rest/v1
SUPABASE_GOTRUE_URL=http://127.0.0.1:${API_PORT}/auth/v1
SUPABASE_STORAGE_URL=http://127.0.0.1:${API_PORT}/storage/v1
SUPABASE_REALTIME_URL=http://127.0.0.1:${API_PORT}/realtime/v1
SUPABASE_ENABLE_SIGNUP=true
SUPABASE_ENABLE_CONFIRM_EMAIL=false
SUPABASE_ENABLE_CONFIRM_PHONE=false
SUPABASE_ENABLE_PASSWORDLESS=true
SUPABASE_AUTH_SITE_URL=http://127.0.0.1:${API_PORT}
SUPABASE_AUTH_ADDITIONAL_REDIRECT_URLS=
SUPABASE_AUTH_JWT_SECRET=$(openssl rand -hex 32)
SUPABASE_AUTH_ENABLE_EMAIL_AUTOCONFIRM=true
SUPABASE_AUTH_ENABLE_ANONYMOUS_USERS=false
SUPABASE_AUTH_EXTERNAL_EMAIL_ENABLED=true
SUPABASE_AUTH_EXTERNAL_EMAIL_FROM=noreply@${DOMAIN}
SUPABASE_AUTH_EXTERNAL_EMAIL_HOST=localhost
SUPABASE_AUTH_EXTERNAL_EMAIL_PORT=25
SUPABASE_EXTERNAL_PORT=${API_PORT}
SUPABASE_DB_PORT=${DB_PORT}
SUPABASE_STUDIO_PORT=${STUDIO_PORT}
SUPABASE_DB_USE_SSL=false
SUPABASE_JWT_SECRET=$(openssl rand -hex 32)
SUPABASE_JWT_EXPIRY=3600
SUPABASE_RATE_LIMIT_MODE=local
SUPABASE_RATE_LIMIT_REQ_PER_SEC=100
SUPABASE_RATE_LIMIT_BURST=200
SUPABASE_ENABLE_CORS=true
SUPABASE_CORS_ORIGIN=https://${DOMAIN},http://localhost:3000
SUPABASE_ENABLE_COMPRESSION=true
SUPABASE_ENABLE_REVERSE_PROXY=true
SUPABASE_PROXY_PORT=54424
SUPABASE_ENABLE_LOG_RETENTION=true
SUPABASE_LOG_RETENTION_DAYS=7
SUPABASE_ENABLE_SWAGGER=true
SUPABASE_ENABLE_OPENAPI=true
SUPABASE_ENABLE_GRAPHQL=true
SUPABASE_ENABLE_REALTIME=true
SUPABASE_ENABLE_STORAGE=true
SUPABASE_ENABLE_AUTH=true
SUPABASE_ENABLE_REST=true
SUPABASE_ENABLE_PGADMIN=false
SUPABASE_ENABLE_MEILISEARCH=false
SUPABASE_ENABLE_IMGBOT=false
SUPABASE_ENABLE_VIDEO=false
SUPABASE_ENABLE_TEXT_TO_IMAGE=false
SUPABASE_ENABLE_EMBEDDINGS=false
SUPABASE_ENABLE_SQL_EDITOR=false
SUPABASE_DB_MAX_CONNECTIONS=100
SUPABASE_DB_SHARED_BUFFERS=256MB
SUPABASE_DB_EFFECTIVE_CACHE_SIZE=768MB
SUPABASE_DB_MAINTENANCE_WORK_MEM=64MB
SUPABASE_DB_WORK_MEM=4MB
SUPABASE_DB_RANDOM_PAGE_COST=1.1
SUPABASE_DB_EFFECTIVE_IO_CONCURRENCY=200
SUPABASE_ENABLE_PG_STAT_STATEMENTS=true
SUPABASE_ENABLE_PG_PARTITIONING=true
SUPABASE_ENABLE_PG_REPLICATION=false
SUPABASE_ENABLE_PG_BACKUP=false
SUPABASE_ENABLE_PG_MONITORING=false
SUPABASE_ENABLE_PG_EXTENSIONS=true
SUPABASE_ENABLE_PG_CRON=false
SUPABASE_ENABLE_PG_UUID=true
SUPABASE_ENABLE_PG_CITEXT=true
SUPABASE_ENABLE_PG_HSTORE=true
SUPABASE_ENABLE_PG_FUZZYSTRMATCH=true
SUPABASE_ENABLE_PG_UNACCENT=true
SUPABASE_ENABLE_PG_TRGM=true
SUPABASE_ENABLE_PG_BTREE_GIST=true
SUPABASE_ENABLE_PG_BTREE_GIN=true
SUPABASE_ENABLE_PG_INTARRAY=true
SUPABASE_ENABLE_PG_TABLEFUNC=true
SUPABASE_ENABLE_PG_LOBUFFUNC=true
SUPABASE_ENABLE_PG_XML2=true
SUPABASE_ENABLE_PG_PARTMAN=false
SUPABASE_ENABLE_PG_PGBOUNCER=true
SUPABASE_PGBOUNCER_POOL_MODE=transaction
SUPABASE_PGBOUNCER_DEFAULT_POOL_SIZE=25
SUPABASE_PGBOUNCER_MAX_CLIENT_CONN=100
SUPABASE_PGBOUNCER_POOL_RESERVE=5
SUPABASE_PGBOUNCER_POOL_RESERVE_TIMEOUT=5
SUPABASE_PGBOUNCER_SERVER_IDLE_TIMEOUT=600
SUPABASE_PGBOUNCER_QUERY_WAIT_TIMEOUT=120
SUPABASE_PGBOUNCER_CONNECT_QUERY=SELECT 1
SUPABASE_PGBOUNCER_AUTH_TYPE=plain
SUPABASE_PGBOUNCER_AUTH_USER=postgres
SUPABASE_PGBOUNCER_AUTH_QUERY=SELECT usename, passwd FROM pg_shadow WHERE usename=$1
SUPABASE_PGBOUNCER_IGNORE_STARTUP_PARAMETERS=extra_float_digits
SUPABASE_ENABLE_PG_PREPARED_STATEMENTS=true
SUPABASE_ENABLE_PG_SESSION_REUSE=true
SUPABASE_ENABLE_PG_STATEMENT_TIMEOUT=30000
SUPABASE_ENABLE_PG_IDLE_IN_TRANSACTION_SESSION_TIMEOUT=60000
SUPABASE_ENABLE_PG_LOCK_TIMEOUT=10000
SUPABASE_ENABLE_PG_LOG_STATEMENTS=ddl
SUPABASE_ENABLE_PG_LOG_MIN_DURATION_STATEMENT=1000
SUPABASE_ENABLE_PG_AUTOVACUUM=true
SUPABASE_ENABLE_PG_AUTOVACUUM_NAPTIME=1min
SUPABASE_ENABLE_PG_AUTOVACUUM_VACUUM_THRESHOLD=50
SUPABASE_ENABLE_PG_AUTOVACUUM_ANALYZE_THRESHOLD=50
SUPABASE_ENABLE_PG_AUTOVACUUM_VACUUM_SCALE_FACTOR=0.2
SUPABASE_ENABLE_PG_AUTOVACUUM_ANALYZE_SCALE_FACTOR=0.1
SUPABASE_ENABLE_PG_AUTOVACUUM_VACUUM_COST_DELAY=20
SUPABASE_ENABLE_PG_AUTOVACUUM_VACUUM_COST_LIMIT=200
SUPABASE_ENABLE_PG_AUTOVACUUM_FREEZE_MIN_AGE=5000000
SUPABASE_ENABLE_PG_AUTOVACUUM_FREEZE_MAX_AGE=200000000
SUPABASE_ENABLE_PG_AUTOVACUUM_MULTIXACT_FREEZE_MIN_AGE=5000000
SUPABASE_ENABLE_PG_AUTOVACUUM_MULTIXACT_FREEZE_MAX_AGE=200000000
SUPABASE_ENABLE_PG_AUTOVACUUM_LOG=true
SUPABASE_ENABLE_PG_AUTOVACUUM_WORK_MEM=-1
SUPABASE_ENABLE_PG_AUTOVACUUM_NWORKERS=2
SUPABASE_ENABLE_PG_AUTOVACUUM_WRITE_AHEAD_LOG=true
SUPABASE_ENABLE_PG_AUTOVACUUM_FSYNC=true
SUPABASE_ENABLE_PG_AUTOVACUUM_FULL_PAGE_WRITES=true
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER=true
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_DELAY=200
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_LRU_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_LRU_MULTIPLIER=2
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_FLUSH_AFTER=0
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP=true
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_INTERVAL=10000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_MAX_WORKERS=2
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_PAGES=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_TIME=1000
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_RETRIES=5
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_RETRY_DELAY=100
SUPABASE_ENABLE_PG_AUTOVACUUM_BG_WRITER_CLEANUP_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_WORKER_MAX_WORKERS=1
SUPABASE_ENV
        chmod 600 "$SUPABASE_DIR/.env"
        ok "Supabase .env created with random secrets"
    else
        ok "Supabase .env already exists"
    fi

    # Start Supabase
    docker compose -p "$SUPABASE_PROJECT" -f "$SUPABASE_DIR/docker-compose.yml" up -d --wait 2>/dev/null || \
    docker compose -p "$SUPABASE_PROJECT" -f "$SUPABASE_DIR/docker-compose.yml" up -d

    ok "Supabase containers started"
}

# ============================================================
# STEP 4: Configure nginx
# ============================================================
step_nginx() {
    info "Step 4/7 — Configuring nginx..."

    local NGINX_CONF="/etc/nginx/sites-available/gestion-monetaria"
    local NGINX_ENABLED="/etc/nginx/sites-enabled/gestion-monetaria"

    # Generate nginx config from template
    sed -e "s/{{DOMAIN}}/$DOMAIN/g" \
        -e "s/{{PORT}}/$APP_PORT/g" \
        "$SCRIPT_DIR/nginx-gestion-monetaria.conf" > "$NGINX_CONF"

    if [[ ! -L "$NGINX_ENABLED" ]]; then
        ln -sf "$NGINX_CONF" "$NGINX_ENABLED"
    fi

    # Remove default site if present
    rm -f /etc/nginx/sites-enabled/default

    nginx -t || { err "nginx configuration test failed"; exit 1; }
    systemctl reload nginx

    ok "nginx configured for $DOMAIN"
}

# ============================================================
# STEP 5: Obtain SSL certificate
# ============================================================
step_ssl() {
    info "Step 5/7 — Obtaining SSL certificate from Let's Encrypt..."

    # Check if certificate already exists
    if [[ -d "/etc/letsencrypt/live/$DOMAIN" ]]; then
        ok "SSL certificate already exists for $DOMAIN"
        return
    fi

    certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos \
        --email "$SSL_EMAIL" --redirect \
        || warn "SSL certificate failed. Run manually: certbot --nginx -d $DOMAIN"

    if [[ -d "/etc/letsencrypt/live/$DOMAIN" ]]; then
        ok "SSL certificate obtained for $DOMAIN"
    fi
}

# ============================================================
# STEP 6: Create systemd service
# ============================================================
step_systemd() {
    info "Step 6/7 — Creating systemd service..."

    local SERVICE_FILE="/etc/systemd/system/gestion-monetaria.service"
    local NODE_BIN
    NODE_BIN="$(command -v node)"

    sed -e "s|{{DEPLOY_PATH}}|$DEPLOY_PATH|g" \
        -e "s|{{NODE_BIN}}|$NODE_BIN|g" \
        -e "s|{{PORT}}|$APP_PORT|g" \
        "$SCRIPT_DIR/gestion-monetaria.service" > "$SERVICE_FILE"

    systemctl daemon-reload
    ok "systemd service created"
}

# ============================================================
# STEP 7: Build and start the app
# ============================================================
step_app() {
    info "Step 7/7 — Building and starting the app..."

    # Copy production env
    cp "$SCRIPT_DIR/.env.production" "$DEPLOY_PATH/.env.production"
    chmod 600 "$DEPLOY_PATH/.env.production"

    cd "$DEPLOY_PATH"

    # Install production dependencies
    npm ci --omit=dev --no-fund --no-audit --loglevel=error

    # Build
    npm run build

    # Enable and start service
    systemctl enable gestion-monetaria
    systemctl restart gestion-monetaria

    ok "App built and service started"
}

# ============================================================
# Summary
# ============================================================
print_summary() {
    echo ""
    echo -e "${GREEN}============================================${NC}"
    echo -e "${GREEN}  GestionMonetaria — Deployment complete!${NC}"
    echo -e "${GREEN}============================================${NC}"
    echo ""
    echo -e "  App:        ${BLUE}https://${DOMAIN}${NC}"
    echo -e "  Supabase:   ${BLUE}http://127.0.0.1:${STUDIO_PORT}${NC}"
    echo -e "             (user: admin / pass: from supabase/.env)"
    echo -e "  Deploy dir: ${YELLOW}${DEPLOY_PATH}${NC}"
    echo -e "  Config:     ${YELLOW}${SCRIPT_DIR}/config.yml${NC}"
    echo ""
    echo -e "  Commands:"
    echo -e "    sudo systemctl status gestion-monetaria"
    echo -e "    sudo journalctl -u gestion-monetaria -f"
    echo -e "    sudo docker compose -p ${SUPABASE_PROJECT} -f ${DEPLOY_PATH}/supabase/docker-compose.yml ps"
    echo ""
    echo -e "  Upgrade:"
    echo -e "    cd ${DEPLOY_PATH} && git pull && npm run build && sudo systemctl restart gestion-monetaria"
    echo ""
}

# ============================================================
# Main
# ============================================================
echo ""
echo -e "${BLUE}╔══════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     GestionMonetaria Bootstrap Script    ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Domain:      ${YELLOW}${DOMAIN}${NC}"
echo -e "  Deploy path: ${YELLOW}${DEPLOY_PATH}${NC}"
echo -e "  Supabase:    ${YELLOW}${SUPABASE_PROJECT}${NC}"
echo ""

step_system
step_repo
step_supabase
step_nginx
step_ssl
step_systemd
step_app

print_summary
